# Generated by Django 3.2.6 on 2022-03-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Settings Key')),
                ('value', models.CharField(max_length=5000, verbose_name='Settings value')),
            ],
        ),
    ]
